export const CONSTANTS = {
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
  SET_FILES: "SET_FILES",
  SET_CURRENT_DIR: "SET_CURRENT_DIR",
  ADD_FILE: "ADD_FILE",
  SET_POPUP_DISPLAY: "SET_POPUP_DISPLAY",
};
